# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfe25e7ff92390088305dab0bc3eaf33fbb264f79a69a056943c42b3e2df45c56cd2c2042fef715eb0dc8c0ee41ed6d40306de7c18d051c093b1a27c19d149f8

test:
  secret_key_base: bcb60f1e7c4f99ce7a57c7929cec8495fb3825c7f11d68aa0d93480552dbf34de4296e5cb85d83d3fa04cc3462fdf0e81d5e0e76410eabb054def79b55f2f3f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
